stages:
  - build
  - review
  - deploy

variables:
  PACKER_VERSION: 1.6.0
  WIN_UPDATE_PROVISIONER_VERSION: 0.9.0

build:
  stage: build
  image: docker:dind
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    # DOCKER_HOST: tcp://localhost:2375
  script:
    - docker build -t tpack:$PACKER_VERSION --build-arg PACKER_VERSION=$PACKER_VERSION --build-arg WIN_UPDATE_PROVISIONER_VERSION=$WIN_UPDATE_PROVISIONER_VERSION .

release:
  stage: deploy
  script:
    - docker --version