image: docker:19.03.12
services:
  - docker:19.03.12-dind
stages:
  - build
  - review
  - deploy

variables:
  PACKER_VERSION: 1.6.0
  WIN_UPDATE_PROVISIONER_VERSION: 0.9.0
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t tpack:$PACKER_VERSION --build-arg PACKER_VERSION=$PACKER_VERSION --build-arg WIN_UPDATE_PROVISIONER_VERSION=$WIN_UPDATE_PROVISIONER_VERSION .

release:
  stage: deploy
  script:
    - docker --version